<template>
  <v-card elevation="5">
    <v-card-text>
      <div class="pa-3">Attendance</div>
      <v-data-table :headers="headers" :items="attendanceRecords">
        <template v-slot:item.status="{ item }">
          <v-icon v-if="item.status === 'Present'" color="green"
            >mdi-check</v-icon
          >
          <v-icon v-else color="red">mdi-close</v-icon>
        </template>
      </v-data-table>
    </v-card-text>
  </v-card>
</template>

<script>
export default {
  data() {
    return {
      headers: [
        { text: "Date", value: "date" },
        { text: "Shift", value: "shift" },
        { text: "In Time", value: "in_time" },
        { text: "Out Time", value: "out_time" },
        { text: "Late In", value: "late_in" },
        { text: "Early Out", value: "early_out" },
        { text: "Total Hours", value: "total_hours" },
        { text: "Overtime", value: "overtime" },
        { text: "Status", value: "status" },
      ],
      attendanceRecords: [
        {
          id: 1,
          date: "2024-11-01",
          shift: "Morning",
          in_time: "08:05",
          out_time: "05:00",
          late_in: "5 min",
          early_out: "0 min",
          total_hours: "8h 55m",
          overtime: "1h",
          status: "Present",
        },
        {
          id: 2,
          date: "2024-11-01",
          shift: "Evening",
          in_time: "02:15",
          out_time: "10:00",
          late_in: "15 min",
          early_out: "10 min",
          total_hours: "7h 35m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 3,
          date: "2024-11-02",
          shift: "Night",
          in_time: "10:00",
          out_time: "06:30",
          late_in: "0 min",
          early_out: "0 min",
          total_hours: "8h 30m",
          overtime: "2h",
          status: "Present",
        },
        {
          id: 4,
          date: "2024-11-02",
          shift: "Morning",
          in_time: "08:00",
          out_time: "04:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "8h",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 5,
          date: "2024-11-03",
          shift: "Evening",
          in_time: "02:30",
          out_time: "10:30",
          late_in: "10 min",
          early_out: "0 min",
          total_hours: "8h",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 6,
          date: "2024-11-03",
          shift: "Night",
          in_time: "10:15",
          out_time: "06:00",
          late_in: "15 min",
          early_out: "0 min",
          total_hours: "7h 45m",
          overtime: "1h 30m",
          status: "Present",
        },
        {
          id: 7,
          date: "2024-11-04",
          shift: "Morning",
          in_time: "08:45",
          out_time: "05:00",
          late_in: "45 min",
          early_out: "0 min",
          total_hours: "8h 15m",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 8,
          date: "2024-11-04",
          shift: "Evening",
          in_time: "02:00",
          out_time: "09:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 9,
          date: "2024-11-05",
          shift: "Night",
          in_time: "10:00",
          out_time: "06:00",
          late_in: "0 min",
          early_out: "0 min",
          total_hours: "8h",
          overtime: "1h 15m",
          status: "Present",
        },
        {
          id: 10,
          date: "2024-11-05",
          shift: "Morning",
          in_time: "07:55",
          out_time: "04:30",
          late_in: "5 min",
          early_out: "0 min",
          total_hours: "8h 35m",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 11,
          date: "2024-11-06",
          shift: "Evening",
          in_time: "03:00",
          out_time: "11:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 12,
          date: "2024-11-06",
          shift: "Night",
          in_time: "09:45",
          out_time: "06:15",
          late_in: "15 min",
          early_out: "0 min",
          total_hours: "7h 30m",
          overtime: "1h 45m",
          status: "Present",
        },
        {
          id: 13,
          date: "2024-11-07",
          shift: "Morning",
          in_time: "08:05",
          out_time: "05:00",
          late_in: "5 min",
          early_out: "0 min",
          total_hours: "8h 55m",
          overtime: "1h",
          status: "Present",
        },
        {
          id: 14,
          date: "2024-11-07",
          shift: "Evening",
          in_time: "02:15",
          out_time: "10:00",
          late_in: "15 min",
          early_out: "10 min",
          total_hours: "7h 35m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 15,
          date: "2024-11-08",
          shift: "Night",
          in_time: "10:00",
          out_time: "06:30",
          late_in: "0 min",
          early_out: "0 min",
          total_hours: "8h 30m",
          overtime: "2h",
          status: "Present",
        },
        {
          id: 16,
          date: "2024-11-08",
          shift: "Morning",
          in_time: "08:00",
          out_time: "04:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "8h",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 17,
          date: "2024-11-09",
          shift: "Evening",
          in_time: "02:30",
          out_time: "10:30",
          late_in: "10 min",
          early_out: "0 min",
          total_hours: "8h",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 18,
          date: "2024-11-09",
          shift: "Night",
          in_time: "10:15",
          out_time: "06:00",
          late_in: "15 min",
          early_out: "0 min",
          total_hours: "7h 45m",
          overtime: "1h 30m",
          status: "Present",
        },
        {
          id: 19,
          date: "2024-11-10",
          shift: "Morning",
          in_time: "08:45",
          out_time: "05:00",
          late_in: "45 min",
          early_out: "0 min",
          total_hours: "8h 15m",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 20,
          date: "2024-11-10",
          shift: "Evening",
          in_time: "02:00",
          out_time: "09:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 21,
          date: "2024-11-11",
          shift: "Night",
          in_time: "10:00",
          out_time: "06:00",
          late_in: "0 min",
          early_out: "0 min",
          total_hours: "8h",
          overtime: "1h 15m",
          status: "Present",
        },
        {
          id: 22,
          date: "2024-11-11",
          shift: "Morning",
          in_time: "07:55",
          out_time: "04:30",
          late_in: "5 min",
          early_out: "0 min",
          total_hours: "8h 35m",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 23,
          date: "2024-11-12",
          shift: "Evening",
          in_time: "03:00",
          out_time: "11:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 24,
          date: "2024-11-12",
          shift: "Night",
          in_time: "09:45",
          out_time: "06:15",
          late_in: "15 min",
          early_out: "0 min",
          total_hours: "7h 30m",
          overtime: "1h 45m",
          status: "Present",
        },
        {
          id: 25,
          date: "2024-11-13",
          shift: "Morning",
          in_time: "08:05",
          out_time: "05:00",
          late_in: "5 min",
          early_out: "0 min",
          total_hours: "8h 55m",
          overtime: "1h",
          status: "Present",
        },
        {
          id: 26,
          date: "2024-11-14",
          shift: "Evening",
          in_time: "02:15",
          out_time: "10:45",
          late_in: "15 min",
          early_out: "15 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 27,
          date: "2024-11-14",
          shift: "Night",
          in_time: "09:30",
          out_time: "06:00",
          late_in: "30 min",
          early_out: "0 min",
          total_hours: "7h 30m",
          overtime: "1h 45m",
          status: "Present",
        },
        {
          id: 28,
          date: "2024-11-15",
          shift: "Morning",
          in_time: "08:00",
          out_time: "04:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "8h",
          overtime: "0h",
          status: "Present",
        },
        {
          id: 29,
          date: "2024-11-15",
          shift: "Evening",
          in_time: "03:00",
          out_time: "11:30",
          late_in: "0 min",
          early_out: "30 min",
          total_hours: "7h 30m",
          overtime: "0h",
          status: "Absent",
        },
        {
          id: 30,
          date: "2024-11-16",
          shift: "Night",
          in_time: "10:15",
          out_time: "06:00",
          late_in: "15 min",
          early_out: "0 min",
          total_hours: "7h 45m",
          overtime: "1h 30m",
          status: "Present",
        },
      ],
    };
  },
};
</script>
